import type { TypeShape } from "../../analyzer/analyze.js";

export const GENERATED_BANNER =
  "// Code generated by soqlc. DO NOT EDIT.\n// Source: SOQL queries processed by soqlc.\n";

export function camelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

export function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? pad + line : line))
    .join("\n");
}

/**
 * Render a TypeShape as a TS type literal. Object shapes become inline
 * `{ key: type; ... }` literals. The optional flag on the OUTER shape is the
 * caller's responsibility (e.g. whether the property uses `?:` or `|`).
 */
export function renderTypeShape(shape: TypeShape): string {
  switch (shape.kind) {
    case "scalar":
      return shape.ts;
    case "object": {
      const entries = Object.entries(shape.fields);
      if (entries.length === 0) return "{}";
      const lines = entries.map(([key, value]) => renderObjectField(key, value));
      return "{\n" + lines.map((l) => "  " + l).join("\n") + "\n}";
    }
    case "subqueryRecord": {
      const inner = renderTypeShape(shape.recordType);
      const body =
        "{\n" +
        indent(`totalSize: number;\ndone: boolean;\nrecords: ${inner}[];`, 2) +
        "\n}";
      return body;
    }
  }
}

function renderObjectField(key: string, value: TypeShape): string {
  const safeKey = isIdentifier(key) ? key : JSON.stringify(key);
  if (value.kind === "subqueryRecord") {
    const inner = renderTypeShape(value);
    const indented = indent(inner, 2).slice(2); // first line already inline
    const sep = value.optional ? "?:" : ":";
    return `${safeKey}${sep} ${indented} | null;`;
  }
  if (value.kind === "object") {
    const inner = renderTypeShape(value);
    const indented = indent(inner, 2).slice(2);
    const sep = value.optional ? "?:" : ":";
    const maybeNull = value.optional ? " | null" : "";
    return `${safeKey}${sep} ${indented}${maybeNull};`;
  }
  // scalar
  const sep = value.optional ? "?:" : ":";
  return `${safeKey}${sep} ${value.ts};`;
}

function isIdentifier(s: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(s);
}
